run_name: DDSP_Extracted
wandb: # Experiment tracking with wandb
  project_name: DDSP_Rochester_Violin # Leave empty for not using wandb
  entity: 'whatever_llc'
data:
  instrument: Violin
  # Path to the audio clips or the created dataset
  path: /home/ubuntu/ddsp_simplified/datasets/rochester_violin_ddsp_extracted
  sample_rate: 16000
  # Duration of a clip
  clip_dur: 4
  # Frame rate at the encoder
  preprocessing_time: 250
  # confidence threshold level for f0
  confidence_threshold: 0.0 # put 0.0 for not using
  # Apply audio normaliztion
  normalize: False
model:
  type: Supervised
  # Frame rate at the decoder
  decoder_time: 1000
  # Use the z encoder or not
  encoder: False
  # Whether to use the reverb module
  reverb: True
  # Directory to save the model in 
  dir:  # leave empty for auto
loss:
  type: spectral
  logmag_weight: 1.0
optimizer:
  name: Adam
  decay_rate: 0.98
  decay_steps: 10000
  lr: 0.001
training:
  batch_size: 32
  epochs: 3000